# Site settings
title: Altaf Ur Rahman
email: mte.altaf@domain.com
url: https://github.com/uraltaf
description: "Welcome to my portfolio, I am working in Machine Learning field from last 7 years. I worked in computer vision for 4 years
, Natural Language Processing for 2 years and Generative AI for 1+ years. My focus is building AI Assistants / AI agents for variety of use cases in day to day business operations"
keywords: "ai agents, ai assistants, ai chatbots, llm, generative ai"
skills: "AI Agent Consultant, AI agent Developer"
meta_author: Rahman Altaf Ur

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/uraltaf/
  - title: leetcode
    url: https://leetcode.com/u/MQgoSqvum6/
  - title: github
    url: http://github.com/uraltaf

# Postal address (add as many lines as necessary)
address:
  - line: Islamabad, Pakistan

# Credits content

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
